local: &local
  encoding: unicode
  adapter: postgresql
  database: dominion_development
  host: localhost
  port: 5432
  pool: 5
  
development:
  encoding: unicode
  adapter: postgresql
  database: dominion_development
  pool: 5